version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:your_password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - /VAR/LIB/POSTGRESQL/DATA:/var/lib/postgresql/data
